### ISSUE TITLE
Allow installation for all users / silent install

### ISSUE THREAD

**Issue by TreeBranches** [GitFiend/Support#1]
OS: Windows

Would be great to have installation switches to give admins the option to install for all users and silent installation. I would like to roll this out to our development team, but am currently extracting the application contents and building our own MSI for this. 

Else uploading this to the Windows Store would work too as I could then Powershell its installation and have the Windows Store handle updates.

**Comment by GitFiend** [comment]
Thanks for the feedback! Sorry I took so long to respond. I've just recently gotten it working in the Windows Store and will be making that available with the next release.

**Comment by GitFiend** [comment]
You can now get it from the Windows Store here: https://www.microsoft.com/en-nz/p/gitfiend/9nmnkltsznkc.
