### ISSUE TITLE
Launch bash from gitfiend

### ISSUE THREAD

**Issue by HatiEth** [GitFiend/Support#10]
Thought it was kind of related to #3 but it is the other way around. Some tasks are taking longer than expected in GitFiend if you are commonly using git bash. But I like the interface for a broader overview and regular tasks.

It would be a nice addition to add a "Launch Git Bash" menu entry, so the repository is opened in bash.

**Comment by GitFiend** [comment]
Thanks HatiEth. I think this is worth adding.
