### ISSUE TITLE
Preserve the historical version.

### ISSUE THREAD

**Issue by cainmagi** [GitFiend/Support#102]
It seems that the historical version will be removed if a new update is released. This will make it difficult to maintain installation scripts. Is it possible to preserve the historical released versions? If not, I suggest that the maintainer could

* Update this program to some public package source, like `apt` on debian, or `apk` on alpine.
* or provide an API for users to download the latest version. For example, instead of using something like this,
  ```
  https://gitfiend.com/resources/GitFiend_0.28.0_amd64.deb
  ```
  It is better to let users download the latest version by
  ```
  https://gitfiend.com/resources/GitFiend?version=latest?os=linux
  ```

**Comment by GitFiend** [comment]
Thanks for the feedback @cainmagi. I'm intending to start preserving the released versions soon, though the download api is a also good idea. I'll look into it.

**Comment by cainmagi** [comment]
Thank you!
