### ISSUE TITLE
0.28 ARM version, not working on mac OSx 11.0.1

### ISSUE THREAD

**Issue by chekobil** [GitFiend/Support#103]
**INTEL version is working fine ...**

White screen with nothing, and this error on Console:
`Aug  5 14:50:08 MacBook-Pro-de-Felipe com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.tobysuggate.gitfiend.5618351.5618561(501)> [14349]
Aug  5 14:50:08 MacBook-Pro-de-Felipe GitFiend Helper (GPU)[16427]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory`

I delete the entire /Application Support/GitFiend folder, and same error
`Aug  5 14:55:37 MacBook-Pro-de-Felipe com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.tobysuggate.gitfiend.5618351.5618561(501)> [14349]
Aug  5 14:55:37 MacBook-Pro-de-Felipe GitFiend Helper (GPU)[16469]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory`

**Maybe the two // on the path ?**
...Resources//GLRendererFloat.....

My system

<img width="314" alt="Captura de pantalla 2021-08-05 a las 14 57 59" src="https://user-images.githubusercontent.com/484052/128353750-9ea30e26-a49c-41b9-92c0-8efed0cdf229.png">

**Comment by GitFiend** [comment]
Thanks for letting me know. Yeah, it could be an issue in my app bundler. Hopefully, updating libraries will fix it, otherwise, this will have to wait until I have an Apple silicon Mac.

**Comment by GitFiend** [comment]
There's now a new Mac app that should work on Apple silicon. I'd love to hear how it works for you.
