### ISSUE TITLE
No partial diffs detected but entire file

### ISSUE THREAD

**Issue by nvaranki** [GitFiend/Support#104]
Starting from version 0.28.0.0, a "Changes" view displays for some files all lines checked on red background, then all lines checked on green background, for entire file. At the same time, the NetBeans version 12.0 correctly indicates local (partial) changes for the same file. I suppose end of line processing has been changed in the program but there's no indication of that issue on the GUI of GitFiend to confirm the source of issue. 
Examination of files with jEdit indicates that problem is limited only to files having CRLF line endings. Files having LF only, show correct local differences.
Explicit setting of next parameter in user's ".gitconfig" has no immediate effect. This setting was absent in initial setup.
[core]
	autocrlf = true
_Platform: Windows 10, encoding cp1251
NetBeans 12.0 LTS
Java: 13; OpenJDK 64-Bit Server VM 13+33
Runtime: OpenJDK Runtime Environment 13+33
Java project encoding: UTF-8_

**Comment by nvaranki** [comment]
Change of line endings for particular file is possible in NetBeans too. Use popup menu on dedicated control, located at far right side of status bar.

**Comment by GitFiend** [comment]
Thanks for the report. Changing line endings in your file will currently result in an unhelpful diff. This does need to be fixed.

**Comment by mbc-audiovisuales** [comment]
Hi, I can confirm whole file diff is highlighted by GitFiend 0.29.0.0. Meanwhile same repo under GitFiend V0.26.0.0 shows the partial diff properly.

Making some changes to simulate a real compound of partial diffs is shown properly in 0.26.0.0 (as it has been over a year for me), but gets shown as whole file diff in GitFiend 0.29.0.0

V 0.26.0.0
![image](https://user-images.githubusercontent.com/71760897/144251217-1b7916b7-6b3e-4d3a-911f-c24e867957d5.png)

V 0.29.0.0
![image](https://user-images.githubusercontent.com/71760897/144251378-052eee86-ea19-4895-be17-8154e5cdca1d.png)

**Comment by mbc-audiovisuales** [comment]
I'm using Sublime 3, under W10 Pro

**Comment by mbc-audiovisuales** [comment]
> Thanks for the report. Changing line endings in your file will currently result in an unhelpful diff. This does need to be fixed.

I think it does need to be fixed, as it is unrelated to line ending special characters. Marking whole file as different when a single character like a letter or a number is added to any line of the document (notice not talking about line ending chars).

Thanks again

**Comment by GitFiend** [comment]
@mbc-audiovisuales There should be a fix out for this soon. In the meantime a workaround is to ensure that both Git and your text editor are outputting files with the same line endings.

**Comment by GitFiend** [comment]
This should now be fixed in v0.30.
