### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by ComfyStoneSlab** [GitFiend/Support#105]
git push
remote: Permission to user/repo to ComfyStoneSlab.
fatal: unable to access 'https://github.com/user/repo.git/': The requested URL returned error: 403

user and repo i replaced them but in the error its the user,repo

**Comment by GitFiend** [comment]
I'm about to release a fix where the credentials dialog could be hidden behind the error message you are seeing. In the meantime, if you can get any credential problem sorted at the command line then GitFiend should work after that.

**Comment by ComfyStoneSlab** [comment]
thx

**Comment by GitFiend** [comment]
This should be fixed now. Let me know if it's still happening.
