### ISSUE TITLE
Please split timeline in branches

### ISSUE THREAD

**Issue by pablodz** [GitFiend/Support#107]
I find really hard to filter commits by branch on gitfiend, some tree visual would be nice, thanks

**Comment by GitFiend** [comment]
Thanks @pablodz, if everything goes well this should be available soon.

**Comment by GitFiend** [comment]
There's now a commit graph in GitFiend v0.30 (as well as a recent feature letting you hide commits that aren't on a particular branch). Hopefully that helps.

**Comment by pablodz** [comment]
Thanks, it works
