### ISSUE TITLE
Toggle file selection by space bar

### ISSUE THREAD

**Issue by lysek** [GitFiend/Support#109]
It would be helpful to toggle selection of whole file (all changes within that file) in file list by space bar while the file list is focused.

Example of usage:
I have a lot of similar small changes and I want to review them, stage and commit. So I use arrow keys to move up and down and see changes but I have to click the checkbox in file list by mouse to select all changes within that file. Because the focused line moves, I have to aim the pointer and that is annoying.

Now the space bar only works when I click directly the checkbox element and the focused checkbox does not change when using arrow keys. It changes the focus of checkbox elements with tab/shift-tab keys but that does not update the changes view on right side.

I am using Linux Mint so maybe it works on Windows or others.

Thanks!

**Comment by lysek** [comment]
I just noticed that I can toggle all changes by pointing the mouse at the checkbox over the changes view, so I do not have move the mouse... but still having both hands on keyboard would be more comfortabe.

**Comment by GitFiend** [comment]
Thanks for the feedback @lysek. This is a good idea and something I want to improve.

**Comment by GitFiend** [comment]
I've improved this in v0.30. Hopefully it helps.
