### ISSUE TITLE
Can't open the app on Apple Silicon

### ISSUE THREAD

**Issue by SincerelyFaust** [GitFiend/Support#110]
Greetings, I have a Macbook Pro with the new M1 CPU and I could not open the Apple Silicon version of the GitFiend app that I downloaded from your site, the Intel x64 version runs fine with Rosetta though.
It says that Apple could not scan the app and that it needs to be updated by the developer.
Would appreciate if you would take a look and let me know if there are any donation links as I'd be looking to make a contributon since I have been a user for a while and I'm very thankful for you work.
Thanks in advance and have a nice day!

**Comment by GitFiend** [comment]
It looks like I exported from Xcode using the wrong button, oops. I've redone this and reuploaded it. Hopefully, that fixes the problem.

Thanks for your nice comments @SincerelyFaust, I really appreciate it. There's no way to donate right now, but this is something i'm thinking about and it's great to hear that GitFiend has been valuable to you.

**Comment by SincerelyFaust** [comment]
I have tried the new one you uploaded and it works flawlessly, thank you!
