### ISSUE TITLE
Stuck on loading after cloning a repository

### ISSUE THREAD

**Issue by SincerelyFaust** [GitFiend/Support#111]
The app successfully clones the repository I want but it's stuck on the loading right after and it doesn't go away.
I'm using the x64, Apple Silicon version of the app on my M1 Macbook Pro.

**Comment by GitFiend** [comment]
Does it let you click ok? Or does it keep spinning and you need to refresh/restart gitfiend?

**Comment by GitFiend** [comment]
Ok, nevermind, I see the issue. Will have a fix soon.

**Comment by SincerelyFaust** [comment]
Thank you
