### ISSUE TITLE
Slow commits loading

### ISSUE THREAD

**Issue by acaruso-syn** [GitFiend/Support#116]
Hi, I updated GitFiend to the latest available for Mac OS (Intel version) and noticed that when I switch repositories, GitFiend shows my changes quickly, but it now takes a long time (even 10 seconds) to load the commits lines it used to load quickly before updating to version 0.31. 
I see this screen for several seconds
<img width="800" alt="Schermata 2022-01-19 alle 12 11 55" src="https://user-images.githubusercontent.com/95630485/150120687-b065e52e-9d34-4edf-be40-ef15a1181df1.png">
after which I can finally see the lines of the commits.
I have noticed this behavior more with repositories that have many commits.
I don't know about the issue and this is certainly not good for me.
Is it possible to fix this behavior?

**Comment by GitFiend** [comment]
Thanks for letting me know. This is probably related to changes I made for the new search feature. Turning the feature off may help somewhat. I care a lot about performance and definitely plan to improve this.

**Comment by acaruso-syn** [comment]
Even if I disable the search feature, the UI is too slow on loading commits and viewing the details of the selected commits. Unfortunately I was forced to downgrade to the previous version because the waiting times are too high :disappointed:

**Comment by GitFiend** [comment]
That makes sense, sorry about the hassle. I'm working on a fix right now.

**Comment by GitFiend** [comment]
@acaruso-syn I've just released GitFiend 0.32.0 with performance improvements for repo loading. Keen to hear if this helps with your issue.

**Comment by acaruso-syn** [comment]
Great! I have updated to the latest version (0.32.0) and now everything works correctly. No more times of high loads and I work fluently. Thank you :grin:
