### ISSUE TITLE
Only stash some files, or stash one file at a time

### ISSUE THREAD

**Issue by SecondFlight** [GitFiend/Support#12]
I have recently found myself wanting to stash my changes such that I could separately preserve and restore
1. broken and/or incomplete code for a feature, and
2. changes for my local dev environment that I do not wish to commit.

This would allow me to switch between feature branches while leaving behind changes that I want to associate with a specific branch but aren't atomic enough to commit.

Thanks so much for your work on GitFiend - it has quickly become my primary Git client for both home and work use. ❤️

**Comment by GitFiend** [comment]
Thanks SecondFlight! This is something I’ve been wanting also. I might move this up in priority.

**Comment by GitFiend** [comment]
I’m currently testing a solution to this. I added an option to let you stash your staged changes. This means you can stash single files or even parts of files (or any combination). If it goes well it’ll be in the next release.

**Comment by SecondFlight** [comment]
That sounds like a fantastic solution 👍
