### ISSUE TITLE
v0.34.0 problems on Centos 7.9

### ISSUE THREAD

**Issue by mehmetakifayas** [GitFiend/Support#126]
Hi,
I just started working with GitFiend v0.34.0 and installed on Centos 7.9 but I am having the following problems:

1. I can not merge branches using the "Merge branch into other" button since it does not appear
2. The little check sign on the checked out branch does not appear
![image](https://user-images.githubusercontent.com/6962855/176947422-8c9e86fa-65bc-4831-8e05-19c5857547fc.png)

3. Diff view is not working. When I add new lines, diff view shows all the lines on green background
![image](https://user-images.githubusercontent.com/6962855/176945547-ce8a38d0-57ff-42a0-b49d-570467eff061.png)

These functionalities work for GitFiend v0.34.0 on Windows 10.

I think I am missing some details out.

**Comment by GitFiend** [comment]
Thanks for the report. It looks like GitFiend has failed to identify HEAD.

Do you know if your local branch is far ahead or far behind your remote repo?

**Comment by mehmetakifayas** [comment]
Hi,
Updating git version from 1.8.3.1 to 2.36 solved the problems.

**Comment by GitFiend** [comment]
Great, thanks. I should put in a warning in about this.
