### ISSUE TITLE
When i press button Fetch the GitFiend always open new browser tab with...

### ISSUE THREAD

**Issue by Myk014** [GitFiend/Support#128]
_Authentication Successful
Git Credential Manager has been successfully authenticated. You may now close this page._

p.s I use git on Bitbucket (Atlassian), new tab opened with next path:
http://localhost:34106/?code=U66eMtBVnPVDzGBJSd&state=fd5dca3927804b738e09877205eb6e1a

**Comment by GitFiend** [comment]
Hi @Myk014, thanks for letting me know. You may be able to get around this by turning off "Use built-in Git" under the "Repo" menu. Also, make sure you have a recent version of Git installed.

**Comment by Myk014** [comment]
It fixed in 0.35.3.0. Thank you @GitFiend
