### ISSUE TITLE
Copy code from GitFiend to other text editor

### ISSUE THREAD

**Issue by Myk014** [GitFiend/Support#129]
![image](https://user-images.githubusercontent.com/47890395/184328431-390a685d-6d67-4422-9ad0-7fe6f37b2217.png)

When i copy some code from _commit_ to any text editor or IDE it is past without specials symbols \n \r \t

So i get next result:
`if(HeadsetAvailable(check)){			setHSdoorMode(Global(set)->doormode);		}`

But i expected:
`if(HeadsetAvailable(check)){`
   `       setHSdoorMode(Global(set)->doormode);`
`} `

I believe that coders use the same code in different projects and copying it from commits is a very important option for git manager. But when you copy a lot of code, it gets pasted as one looooong line :)

**Comment by GitFiend** [comment]
Hi @Myk014. Thanks for the report. This is definitely on my list of things to fix.
