### ISSUE TITLE
'New Repo' button on startup

### ISSUE THREAD

**Issue by naclomi** [GitFiend/Support#130]
Hello! I was wondering if it would be possible to add a 'Create a repo' button on the startup screen along side the 'Open' and 'Clone' buttons?

I'm considering using GitFiend as a tool to teach Git to a class of non-programmers, and while I can accomplish the above by telling them to hit "Ctrl+Shift+N", it would be nice to have a GUI equivalent to that action in front of them (and save me having to tell Mac users to use command, rather than control).

**Comment by naclomi** [comment]
(this is a SPECTACULAR tool, by the way -- thank you so much for making it freely available and cross-platform)

**Comment by GitFiend** [comment]
Hi @naclomi, thanks for the feedback! I think I can do this. 

Now that you bring this up, I think there’s also a bug in that you should be able to see and access the file menu on Windows when there's no repo open. I will try and get a fix for this out soon.

**Comment by GitFiend** [comment]
I've just released GitFiend 0.36 which includes this change. Hopefully it helps.

**Comment by naclomi** [comment]
Indeed it does! Thank you so much :blush:
