### ISSUE TITLE
labeling of the branches not correct

### ISSUE THREAD

**Issue by Tealk** [GitFiend/Support#131]
in the branch overview origin/ is shown 2 times instead of upstrame/ and origin/

![image](https://user-images.githubusercontent.com/12276250/185738016-57233239-36a1-4093-b1f3-4e6d543293da.png)

**Comment by GitFiend** [comment]
Thanks for reporting this @Tealk. I've come up with a fix and it'll be in the next release.

**Comment by GitFiend** [comment]
This should now be fixed in v0.36.
