### ISSUE TITLE
v0.35.3 glibc dependency problem on Centos 7.9

### ISSUE THREAD

**Issue by mehmetakifayas** [GitFiend/Support#132]
Hi,
I'm using GitFiend on Centos 7.9. GitFiend v0.35.3 does not work on Centos 7.9 since the rust-server requires glibc version 2.29. 
You can see the log below.

/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server true
/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server)
/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server)
/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server)
/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server)

**Comment by GitFiend** [comment]
Thanks for reporting this. I'll see if it can get a fix out soon.

**Comment by farrukh-dplit** [comment]
Exactly same issue with Ubuntu 18.04.

**Comment by GitFiend** [comment]
I've just release GitFiend 0.36 which should fix this. Let me know if it's still an issue.

**Comment by mehmetakifayas** [comment]
Hi,
Thank you for the new release. After updating to v0.36 GitFiend works now but when I click on the changed file, the differences view does not show up. Also when I minimize the GitFiend window, content of Changes/Commits/Branches tabs disappear.
You can see the log below.

/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server true
PORT:37645

thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/git/queries/refs.rs:16:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

101

**Comment by GitFiend** [comment]
Thanks for the quick feedback and providing the log. I've created a build that will hopefully fix this and uploaded it to github here: https://github.com/GitFiend/Support/releases/tag/0.36.1

If this works I'll release it, otherwise keep looking into it.

**Comment by mehmetakifayas** [comment]
Thank you. v0.36.1 works!

**Comment by farrukh-dplit** [comment]
0.36 seems functional, thank you for quick fix.

**Comment by mehmetakifayas** [comment]
Hi,
I know this is a little bit late to report but when I open v0.36.1 in another VM (Centos 7.9) error window pop ups.

The message is: “Couldn’t find Git. If you are installing Git, wait for the install to finish, then try again”.

Git 2.37 is already installed. I don’t know why gitfiend could not find the directory.

**Comment by GitFiend** [comment]
That's strange. Gitfiend just calls git and assumes it's in your path. It's possible the reload button in that dialog is no longer working due to my recent changes and you may need to restart (if you haven't already tried that).

**Comment by mehmetakifayas** [comment]
Restarting VM didn’t work. I cleaned everything related to GitFiend and re-installed but that couldn’t solve the problem. Interestingly only 1 over 3 VM causes this problem.

**Comment by GitFiend** [comment]
What do you get exactly when you run "git version" in a terminal? I noticed something a little dumb in my version checking code and made a fix and another build: https://github.com/GitFiend/Support/releases/tag/0.36.2. There's a chance this will fix it.

**Comment by mehmetakifayas** [comment]
Hi,
v0.36.3 worked. There was not only version numbers but also characters as suffix in my git version (I know the reason). After updating git version to 2.37.3, both v0.36.1 and v0.36.3 worked in this VM.
Thank you!
