### ISSUE TITLE
Writing to the terminal

### ISSUE THREAD

**Issue by ebbek** [GitFiend/Support#133]
Hi

This may be a duplicate of issue #71 although I do think the problem is a little different.

Platform: Ubuntu 22.04.1 in WSL with an X410 X-server running in Windows so all programs are started from the command line.

When I start gitfiend from the terminal as follows:

`gitfiend . & disown $!`

letting it get up and running and closing it immediately after it is ready, I get this output in the terminal:

`$ /opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server true`
`[5512:0823/160730.927416:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket`
`/run/dbus/system_bus_socket: No such file or directory`
`[5512:0823/160730.927494:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`
`[5512:0823/160730.932207:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
`[5512:0823/160730.932318:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
`PORT:38971`

`[5512:0823/160731.007100:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
`[5566:0823/160734.170317:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization`
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
`[5629:0823/160742.494535:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.`
`[5629:0823/160742.497595:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.`
`[5582:0823/160742.500491:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.`
`{ argsResult: { repoPath: '/home/ebkr/tools/devenv' } }`
`Took 0ms to scan`

`StdErr: ""`

`StdErr: "fatal: ambiguous argument 'stash': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n"`
`Took 1ms to request stashes from Git`

`Took 16ms to request 1000 commits from Git`

`Took 2ms to parse 1000 commits. Length 154699`
`Took 19ms to request stashes and commits from Git`

`Took 0ms to get refs from commits *****`

`Took 0ms to filter commits`

`Took 2ms to read and parse patches. Length 426585.`

`Took 1ms to put patches in temp cache (load).`

`StdErr: ""`
`Failed to get patches for commit 5dcc9d30974478b83bea80202842050c6696ca5d`

`StdErr: ""`
`Failed to get patches for commit 1379ecde26f218fb94e87c4384cc1a965a760faa`

`StdErr: ""`
`Failed to get patches for commit 5dec4017f87bd31b431468348b1e6067d0c04cca`

`StdErr: ""`
`Failed to get patches for commit 735aff803c5f0651ffa922e68c3be50805df625a`

`StdErr: ""`
`Failed to get patches for commit 8315500eea44740402bda9c09a82b9e2f33fa7b6`

`Took 1ms to put patches in temp cache (write).`

`Wrote patches to 'Some("/home/ebkr/.cache/gitfiend/patches/homeebkrtoolsdevenv.json")'`

`Took 19ms for load_patches`

`get_un_pushed_commits_computed Took 0ms`

`[5512:0823/160742.729069:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
`Took 4ms for calc_ref_diffs`

`StdErr: ""`

`StdErr: "fatal: ambiguous argument 'stash': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n"`
`Took 1ms to request stashes from Git`

`Took 14ms to request 1000 commits from Git`

`Took 2ms to parse 1000 commits. Length 154699`
`Took 16ms to request stashes and commits from Git`

`Took 0ms to get refs from commits *****`

`Took 0ms to filter commits`

`StdErr: ""`
`Failed to get patches for commit 5dcc9d30974478b83bea80202842050c6696ca5d`

`StdErr: ""`
`Failed to get patches for commit 1379ecde26f218fb94e87c4384cc1a965a760faa`

`StdErr: ""`
`Failed to get patches for commit 5dec4017f87bd31b431468348b1e6067d0c04cca`

`StdErr: ""`
`Failed to get patches for commit 735aff803c5f0651ffa922e68c3be50805df625a`

`StdErr: ""`
`Failed to get patches for commit 8315500eea44740402bda9c09a82b9e2f33fa7b6`

`Took 0ms to put patches in temp cache (write).`

``Wrote patches to 'Some("/home/ebkr/.cache/gitfiend/patches/homeebkrtoolsdevenv.json")'`

`Took 11ms for load_patches`

`get_un_pushed_commits_computed Took 0ms`

`Took 0ms for calc_ref_diffs`

`will quit`
`null`

If I actually **use** gitfiend for something I will get a lot more.

I have tried redirecting both `stderr` and `stdout` to `/dev/null` in various ways but I have not managed to avoid output as shown above.

**Comment by GitFiend** [comment]
Thanks for letting me know you use GitFiend this way. I can certainly make this a lot less noisey.

**Comment by ebbek** [comment]
Hi Toby

FYI: This bash function does the trick for me for now:

# Open gitfiend
function gitf() {
  ( gitfiend 2>&1 > /dev/null ) 2>&1 > /dev/null &
}

Best regards

Ebbe Kristensen

Den ons. 24. aug. 2022 kl. 10.10 skrev Toby Suggate <
***@***.***>:

**Comment by GitFiend** [comment]
Great thanks. I've also reduced the amount of output a lot in the latest release.
