### ISSUE TITLE
Where is the repo with GitFiend source code?

### ISSUE THREAD

**Issue by mediaexplorer74** [GitFiend/Support#136]
Hello, Toby.

Where is the repo with GitFiend source code?

**Comment by GitFiend** [comment]
Hi @mediaexplorer74. The repo is currently private.

**Comment by mediaexplorer74** [comment]
Hi @GitFiend. Ok, Private New Zeland properties and other politics not interested to me.
What coding language you used? Not C#? It's not friendly. So, goodbye!
