### ISSUE TITLE
Merge conflict view issue - Release 0.37.2

### ISSUE THREAD

**Issue by manjunathav** [GitFiend/Support#138]
Merge conflict view shows empty in left and right side views.

**Comment by GitFiend** [comment]
Thanks for letting me know. I have seen this happen to someone else once before but it's not happened to me. Any more details on how to reproduce it reliably would be really helpful.

**Comment by GitFiend** [comment]
Thanks, I'll take a look at this soon.

**Comment by GitFiend** [comment]
I've just released a beta with a fix for this when the file is an image (https://gitfiend.com/all-downloads). I'll look into non-image binaries next.

**Comment by GitFiend** [comment]
This should now be fixed in v0.39.4
