### ISSUE TITLE
Couldn't find git

### ISSUE THREAD

**Issue by Hankslab-ABG** [GitFiend/Support#140]
Greetings,

I'm relatively new to git and want to use GitFiend to help with merge conflicts (as this is a pain in GitBash). I had GitFiend working but had to force close it and git after it froze switching between branches. When I tried opening it again, it couldn't not find git. I uninstalled git and GitFiend, installed the newest version of git, but GitFiend still can't find it. Is there some way to point it to the correct directory or do I need to do some sort of more thorough uninstall of git and/or GitFiend?

Thanks,

Adam

**Comment by GitFiend** [comment]
Hi @Hankslab-ABG, sorry to hear about your trouble.

It sounds like you are using Windows?

If you run `git --version` in cmd.exe you should see a version printed out. If this works then GitFiend should also work.

I'm surprised to hear it froze when you were switching branches, though this could mean you were on version 0.37. The latest version is 0.38 which should hopefully fix issues with the progress dialog never finishing.

**Comment by Hankslab-ABG** [comment]
Thanks for your quick reply.

When I run that command in gitBash I get git version 2.38.1.windows.1. The command doesn't work in command prompt. Is that perhaps part of the issue?

**Comment by GitFiend** [comment]
Yeah, it means that git isn't set in Path in your environment variables. I think the git installer asks whether you want it added when you run it and maybe you said no or that you only want to use gitbash? Otherwise you can add it manually in system settings.

**Comment by GitFiend** [comment]
It could be this: 
![image](https://user-images.githubusercontent.com/47970508/197656988-f0187729-7af9-42af-8e5c-e9c2da461ec4.png)
I think GitFiend won't work if you select option 1.

**Comment by Hankslab-ABG** [comment]
This did the trick! I had actually tried to add the path to the environment variables manually, but I had just pointed it to the git folder itself rather than the cmd subfolder within it. Once I change it I was able to get GitFiend to load again.

Thanks so much! Looking forward to using this again.
