### ISSUE TITLE
Commits view - align branches and date

### ISSUE THREAD

**Issue by martin8877** [GitFiend/Support#142]
Hi, 
can we align branches to the right and date to the left in commits views? It's difficult to match commit text with branch or date when window is wide.

![Screenshot_20221121_103444](https://user-images.githubusercontent.com/23344526/203018982-67b5dc52-dbee-4748-8c1e-1fdd2cdf3c81.png)

**Comment by GitFiend** [comment]
Yeah, this could be improved for wide screens/windows.

**Comment by GitFiend** [comment]
This has been improved in a recent update.
