### ISSUE TITLE
Support arm64 architecture for Linux

### ISSUE THREAD

**Issue by Myk014** [GitFiend/Support#143]
Hello! I opened **GitFiend** half year ago and **LOVED** it so much, thanks you for that! 

I'm Qt cross platform developer for embedded systems and some weak ago i migrated from Intel to M1 processor on my Mac and i use parallel desktop to run Debian 11.3 with arm64 architecture and was very upset because i cannot run GitFiend on this Debian  and cannot install common Debian on this Mac. **Is it possible to make build with arm64 architecture for Linux?** 

I know than Chromium browser successful work on Debian with arm64 from default repository. I can help you with test if u need! Linux with arm64 is very popular in embedded systems`s world...

`bash: ./GitFiend-0.38.3.AppImage: cannot execute binary file: Exec format error`

**Comment by GitFiend** [comment]
Hi Myk014, I was able to make a build (tested in ubuntu in parallels on Apple silicon): https://github.com/GitFiend/Support/releases/tag/0.39.1

**Comment by Myk014** [comment]
It work successfully! I will use it every day and if i find some bugs i will tell you immediately. Thanks you so much!

**Comment by GitFiend** [comment]
Great, thanks. If all goes well I'll make this part of regular releases.
