### ISSUE TITLE
Last changes not showing in the commit view

### ISSUE THREAD

**Issue by aurelhann** [GitFiend/Support#146]
When I'll commit some changes with gitfiend the commit view show me nothing

![image](https://user-images.githubusercontent.com/24210502/214829279-8926442f-6df7-48f4-95a6-1e145a98f729.png)

but git cli says me the real diff

![image](https://user-images.githubusercontent.com/24210502/214829754-e078c394-51b3-4d2f-869c-a7f45c936583.png)

What's happening?

v0.38.3

**Comment by GitFiend** [comment]
I'm not sure what's going on. Sometimes a merge commit can be empty, or sometimes the files can take a while to load in n large repos, but that's probably not the case here. 

You could try "clear cache and reload" from the view menu.

Also, what version of git do you have installed?

**Comment by aurelhann** [comment]
I have already reload , clear cache, reload, restart the app. Nothing happens differently.

Interesting thing. If I push to remote the changes appear again: :shrug: 

my version of git 

`git version 2.39.0`

**Comment by GitFiend** [comment]
Thanks for the info. I've made some fixes in that area that aren't in 38.3. Does the beta have the same issue? You can get it at https://gitfiend.com/all-downloads

**Comment by aurelhann** [comment]
same with 0.39.3 beta

![image](https://user-images.githubusercontent.com/24210502/216261747-a3850b67-2af7-44a0-a56e-3f3e13b8c985.png)

![image](https://user-images.githubusercontent.com/24210502/216262122-3de3d316-8b4f-430c-954d-3364d97f80b4.png)

**Comment by GitFiend** [comment]
The command I'm using for loading the changed files in a typical commit is basically:
`git log --remotes --name-status --pretty=format:%H --no-merges -n5`

If you run that, do you get files for the most recent commit?

**Comment by aurelhann** [comment]
I'll try tomorrow

**Comment by GitFiend** [comment]
Ok, I've managed to reproduce this just now. Testing a fix for it.

**Comment by GitFiend** [comment]
I've just created a new beta which should fix this (v0.40.0): https://gitfiend.com/all-downloads

**Comment by aurelhann** [comment]
Work's fine now. Many thanks.
