### ISSUE TITLE
Error on WSL2(G)

### ISSUE THREAD

**Issue by maliakos** [GitFiend/Support#149]
Hello and thank you for an amazing piece of software. I've been using it for some months and love it.
Currently I'm running a setup on Windows 11 on WSL2 where my editor(PHPStorm if it matters) + gitfiend are being displayed with https://github.com/microsoft/wslg. I have assigned 8GB of RAM on wsl . At some occasions(Only but not necessarily when 2 editor windows are open e.g. sometimes it works fine ) when i try to open gitfiend throught WSL(3 wslg windows in total open) i get the following error:
(Output of --trace-warnings)

```
/opt/GitFiend/resources/app.asar.unpacked/output-code/core/rust-server true
PORT:43917

(node:17175) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///opt/GitFiend/resources/app.asar/resources/index.html?port=43917'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:390:28)
(Use `gitfiend --trace-warnings ...` to show where the warning was created)
(node:17175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
I am suspecting it has to do with wslg limitations but i am not familiar with node/electron errors + debugging and even less with  wslg debugging. Please close/ignore if it's related to my setup.( Memory reaching it's limits when multiple wslg windows open ? )

**Comment by GitFiend** [comment]
Thanks maliakos, It's awesome to hear you love the app.

You are running GitFiend in an environment that I haven't really tested. I've done a little testing of GitFiend with WSL, but that was using the windows version and pointing it at the repo in WSL. I will take a look and see if I can reproduce the problem when I get a chance.

**Comment by GitFiend** [comment]
I don't think it's memory related (especially since GitFiend doesn't use much memory ~100Mb). I set WSL to a limit of 2Gb, filled it up and then opened GitFiend without issue. After some digging it looks like cypress have the same issue meaning it could be electron, maybe specific versions. I wasn't able to reproduce the issue with the latest beta, so you could try that: https://gitfiend.com/all-downloads

**Comment by maliakos** [comment]
Sorry it took me a while to update. I now believe it has nothing to do with Gitfiend since I had the same happen to me on PHPstorm when running on WSLG. It must be a WSLg related bug which I cannot reproduce either reliably. If it matters , my assumption is there is a bug on WSLg related to waking up from sleep.
