### ISSUE TITLE
Windows 7 installer

### ISSUE THREAD

**Issue by picoloto** [GitFiend/Support#15]
Is there an installer for windows 7?

**Comment by GitFiend** [comment]
No there isn’t sorry. I could provide an installer, but it wouldn’t be signed, and wouldn’t have automatic updates. I don’t mind doing this if there’s enough interest.

**Comment by preeteshjain** [comment]
For me, the Windows 10 Store doesn't install any app for some reason. It's pretty buggy. It would be nice if there's a download page for .exe files. If there's an update people can download it manually and update like other software on Windows.

**Comment by picoloto** [comment]
For me it is the same. The installer provided by the site is very important. even VS code does that and is handy to use.
Would you have that possibility?

**Comment by alspadoni** [comment]
Please provide an installer different than the one downloaded from the MS Store as I can't install from the store using company email address.

**Comment by GitFiend** [comment]
There’s now a separate installer for those who can’t or don’t want to use the Microsoft store.

**Comment by preeteshjain** [comment]
Thanks a lot!

**Comment by ordnaelmedeiros** [comment]
Thanks a lot!
