### ISSUE TITLE
0.39.4 - Workspace / Multi Repository View Wild Colors

### ISSUE THREAD

**Issue by codesplode** [GitFiend/Support#151]
Thank you for a great piece of software. I look forward to seeing where you take this and have been testing it for a while now. If you open source it I would love to support you more with code and or donations.

The latest release with the search out of beta is great, but I'm probably going to have to rollback because I use the workspaces / folder view feature to list many repositories and the latest release colors them so wildly they are hard to read and scrolling makes my brain hurt haha. I believe this is probably a development / testing change that made it into the release. See image below:

![image](https://user-images.githubusercontent.com/823828/218288287-8934f033-b5f6-461d-b621-950c9a3a3136.png)

Please let me know if I can help resolve this issue in any way!

**Comment by GitFiend** [comment]
Thanks. Yeah, that is a bit much. As workspaces are a preview feature, I'm still figuring out what they should look like. It's cool how many people I see already using it though.

I've made a new build that tones it down (v0.40.0): https://gitfiend.com/all-downloads

**Comment by codesplode** [comment]
Thank you, the muted colors helps a lot and I'll hold my comments on any of it until you get it where you think it should be. The quick release is very much appreciated and let me know where to send you your desired beverage when you are ready!
