### ISSUE TITLE
Request: Publish GitFiend on Flathub

### ISSUE THREAD

**Issue by priahoud** [GitFiend/Support#152]
I would love to being able to install GitFiend from [Flathub](https://flathub.org) and I think others would want that too.

Just in case you don't know, their [About Page](https://flathub.org/about) says:

_"Flathub aims to be the place to get and distribute apps for Linux. It is powered by [Flatpak](https://flatpak.org) which allows Flathub apps to run on almost any Linux distribution."_

You can see from their [statistics](https://beta.flathub.org/statistics) that they are currently distributing nearly 2000 Applications with ~2 Millon downloads per day all over the World.

Because Flatpak in itself is such a huge topic, I will just link to their [documentation](https://docs.flatpak.org/en/latest/index.html) if you want to dig deeper into the topic.

To get things rolling, I created an [initial repository](https://github.com/priahoud/flathub/tree/com.gitfiend.GitFiend) in my Github Account following their [App Submission](https://github.com/flathub/flathub/wiki/App-Submission), [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements) and [App Maintenance](https://github.com/flathub/flathub/wiki/App-Maintenance) Wiki pages - working and ready to be sent as a pull request to be included into their App catalog.

This repository is just to show you the results and give you a chance to inspect, critique or veto the effort. **I will, of course, remove it immediately if you don't want it online for any reason.**

Included are:
- a [YAML manifest](https://docs.flatpak.org/en/latest/manifests.html) file describing the parameters for building the application. Because GitFiend is a proprietary application, it cannot be distributed the "normal" way legally on Flathub, which is to build the application from source and include it in the distributed container. Instead it is included as an ["extra-data" source](https://docs.flatpak.org/en/latest/conventions.html#exporting-through-extra-data), which is data that will only be downloaded at install time. I chose to reuse the AppImage files from the website because they also come in arm64 variants, which is supported by Flapak/Flathub. A really nice thing to have are the "x-checker-data" entries with instructions for [Flatpak External Data Checker](https://github.com/flathub/flatpak-external-data-checker#html-checker) to periodically look for new releases on the website and automatically create PRs for the repository to include these new releases. This behaviour can even be extended to also [automatically merge](https://github.com/flathub/flatpak-external-data-checker#automatically-merging-prs) those PRs (currently not enabled in this repository, but easy to do), which would fully automate the whole process because the Flathub CI/CD pipeline is configured to create new builds after a successful merge and publish the new build ~3 Hours later.
- an [AppStream](https://www.freedesktop.org/software/appstream/docs) file, which is a [Freedesktop](https://www.freedesktop.org) standard for defining additional metadata for Linux applications. It is necessary for any Linux Store-Applications and -Websites like [GNOME Software](https://apps.gnome.org/de/app/org.gnome.Software), [KDE Discover](https://apps.kde.org/de/discover) [Flathub](https://flathub.org), [KDE Apps](https://apps.kde.org), [Elementary Appcenter](https://appcenter.elementary.io) and the [Snapcraft Store](https://snapcraft.io/store) to display useful information about your application. I tried to be as thorough as possible with the included data, but you may want to change some things in there. Examples would be the metadata license (currently [CC0-1.0](https://creativecommons.org/publicdomain/zero/1.0), which is suggested by the [App Submission](https://github.com/flathub/flathub/wiki/App-Requirements#appstream) wiki page if the file is not provided by the upstream), the description of the application, which is currently just the feature-matrix from the website copied over and adapted to the limited styling allowed in appstream files, or the screenshots section, which currently only includes the [Linux screenshot from the website](https://gitfiend.com/resources/home-lin.png).
- a [Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) file, customised to work with the Flatpak container.
- a SVG file downloaded [from your website](https://gitfiend.com/resources/icon.svg) in order to be able to display an icon in the App Stores and on the [Flathub website](https://flathub.org) (remember, the actual AppImages from the website are only downloaded at install time - so the icons included in there can't be displayed in the Stores). I think we would need a License file with explicit distribution permission to include this in the repository.
- a flathub.json file to instruct the CI/CD pipeline to only build and publish for x86_64 and aarch64

Note that ideally, the AppStream and the Desktop files should [not be distributed](https://github.com/flathub/flathub/wiki/App-Maintenance#acceptable-but-should-be-submitted-upstream) in this repository, but in a separate one provided and maintained by the upstream because they are useful for any Linux Store - not just Flathub! The same is probably true for the Icon file because of the problems mentioned in the list above in case of a non-distributable proprietary app like GitFiend.

Anyway, I made sure the build works by testing it locally and I think this is a good starting point for an initial submission to Flathub and if you want to, I will gladly hand the whole repository over to you.

What do you think?

**Comment by GitFiend** [comment]
This is cool, thanks @priahoud. I would like to get GitFiend onto Flathub but it seemed like too much time investment last time I looked.

**Comment by priahoud** [comment]
Allright! Lets try it then.

**Comment by priahoud** [comment]
Closing this as GitFiend is [available on Flathub](https://flathub.org/en/apps/com.gitfiend.GitFiend)!

[Package Source at GitHub](https://github.com/flathub/com.gitfiend.GitFiend)
