### ISSUE TITLE
Commits with renamed files appear as only "deleted" lines

### ISSUE THREAD

**Issue by ZaLiTHkA** [GitFiend/Support#154]
greetings.. I haven't actually used GitFiend for a while, came back to it again the other day because, well, it's just so slick.. 😎  thanks Toby!

I did find one small bug in the "commit details view" just now, where after simply commiting a file rename, I thought my file had somehow been deleted instead...

---

I did manage to [reproduce it](https://github.com/ZaLiTHkA/gitfiend-rename-issue-test): I started with a dummy `README.me` file in the first commit, then renamed it to `NOT_ACTUALLY_README.md` in the second.

the initial and "expanded" commit list view does show an "R" on the right, indicating a rename, but no mention of what it was renamed _from_:

![2023-02-27 18_58_37-C__Users_littl_workspace_TEMP_gitfiend-rename-issue-test](https://user-images.githubusercontent.com/2149312/221631327-e10ae0a3-0eb3-4c94-843b-2e115bdb99fe.png)

then it gets more concerning when you open that commit to view the individual changes, where it shows the new file name with all lines being deleted:

![2023-02-27 18_58_54-C__Users_littl_workspace_TEMP_gitfiend-rename-issue-test](https://user-images.githubusercontent.com/2149312/221631246-d0c35c18-4b97-47b8-a3e6-7be00b358788.png)

---

just for comparison, Git Fork (much less slick, but very stable and powerful) shows it as follows:

![2023-02-27 19_02_01-Fork](https://user-images.githubusercontent.com/2149312/221632448-f682d9db-fe54-43bd-b8f4-aa09187ccf76.png)

**Comment by GitFiend** [comment]
Thanks for the helpful writeup @ZaLiTHkA. I had a look into this today and think I have a fix.
