### ISSUE TITLE
Large repositories cause significant problems

### ISSUE THREAD

**Issue by avsdev-cw** [GitFiend/Support#162]
An example repository that GitFiend can't seem to handle is: https://github.com/userfrosting/UserFrosting

NOTE: I am on the beta release at the moment.

**Comment by GitFiend** [comment]
Thanks for the example repo. I noticed the files in a commit were taking ages to load and I've got a fix for that coming soon.

**Comment by GitFiend** [comment]
Just released a new version of gitfiend that should improve this. Let me know if the issue is still there (and details)

**Comment by avsdev-cw** [comment]
This seems to be solved my end, many thanks!
