### ISSUE TITLE
should be expand all branches in commits tab

### ISSUE THREAD

**Issue by minh98** [GitFiend/Support#18]

**Comment by GitFiend** [comment]
Hi minh98. Could you please explain some more? Is this about the text “show all branches...”?

**Comment by minh98** [comment]
![Screenshot from 2019-09-29 15-08-29](https://user-images.githubusercontent.com/26597466/65828990-0d3f4700-e2cb-11e9-937f-58650c72debe.png)
i want to show all branches by default. like it 
![Screenshot from 2019-09-29 15-08-32](https://user-images.githubusercontent.com/26597466/65829013-32cc5080-e2cb-11e9-91f7-e07a85a54bd1.png)

i can see all branches and status of them without hovering over

**Comment by GitFiend** [comment]
Why not just go into the branches view? (You can access it from the toolbar, a branch or the main menu). The hover is just so you can peek to see which other branches are on that commit without going into the branches view.

**Comment by minh98** [comment]
I am used to using other tools like gitkraken, sourcetree, gittower .. and they display all branches with their commit history. I feel that is very convenient

**Comment by GitFiend** [comment]
I think there may have been a missunderstanding here. GitFiend does the same thing as other Git clients. In your example, you have all branches pointing at one commit, that is why they are collapsed. You have given me an idea though. I should expand them when you expand the commit.
