### ISSUE TITLE
Missing Date Field!

### ISSUE THREAD

**Issue by fenice-csw** [GitFiend/Support#22]
Date field is most important in a code versioning program and is missing in the commit detail section. It is also useful in the commit list section if the commit has been pushed 1 or two days before.
Don't you think it's appropriate to include it?

**Comment by GitFiend** [comment]
I agree. I like having time since in the commit list, but I think it should have the actual date when you look at a commit. I'll see if I can get this into the next release.

**Comment by keymasterr** [comment]
It might be a tooltip when hovering the time badges on the Commit tab also

**Comment by GitFiend** [comment]
For the next release i'm just adding a tooltip with the full date when you hover over a relative date. I plan to make a bigger change soon when I rethink the expanded commit card layout.
