### ISSUE TITLE
Merge branch

### ISSUE THREAD

**Issue by rombru** [GitFiend/Support#24]
Is it possible to merge branch ? Or, will it be possible in the future ?

**Comment by tsuggate** [comment]
Is this what you mean?

<img width="530" alt="Annotation 2019-10-18 113651" src="https://user-images.githubusercontent.com/19199926/67052758-a01d2400-f19b-11e9-9379-17a6ca58b943.png">

**Comment by rombru** [comment]
Yes ! Don't know why it didn't worked for me before, but apparently it works now. Probably a misuse of mine. Thank you.
