### ISSUE TITLE
Make stage sidebar adjustable

### ISSUE THREAD

**Issue by HannesDev** [GitFiend/Support#29]
Hi Toby,
we're sometimes having some subfolders or longer file names as usual, which can't be seen in the Staged side bar. Would be great, if width of the sidebar would be ajustable.
Another idea would be tool tips.
![image](https://user-images.githubusercontent.com/17861443/67576944-d7617700-f73f-11e9-92d8-e9e79802e820.png)

Cheers!

**Comment by GitFiend** [comment]
Hi HannesDev, 

I've been putting this off in favour of other things for a while, but will hopefully get to it soon. The tooltip is a good idea and can do that now/next release.

Thanks

**Comment by GitFiend** [comment]
You can now do this in v0.22.
