### ISSUE TITLE
Please make youtube videos, to know if it's worth installing or not.

### ISSUE THREAD

**Issue by sapioit** [GitFiend/Support#3]
It would also serve as advertising, and so google won't change my search from "GitFiend" to "GirilFriend"...

**Comment by AshrafJaddo** [comment]
It is free to install, better to try it yourself on your own repo and workflow to see if it works for you.

**Comment by sapioit** [comment]
Might be better, but I'm not going to try it until I see how it works in a video. Same goes for almost all (new for me) apps before I install them.

**Comment by sapioit** [comment]
Plus that making a 2-5 minutes long video should not take more than 20 minutes to record and upload on youtube.

**Comment by GitFiend** [comment]
Thanks. This and our discussion on twitter has convinced me that youtube is a good next place to put some info on GitFiend. 

Now that I think about it, the last new app I started using was Affinity Designer, and I watched youtube videos before trying and buying.

**Comment by sapioit** [comment]
Thanks for making this decision!

**Comment by GitFiend** [comment]
Here's a simple video showing GitFiend: https://www.youtube.com/watch?v=EtkqHDOi0gE

**Comment by sapioit** [comment]
Thanks for making this decision!
