### ISSUE TITLE
Select multiple lines in changes viewer

### ISSUE THREAD

**Issue by aaaidan** [GitFiend/Support#36]
It would be helpful to be able to select multiple lines in order to [un]stage or discard more than one line at a time.

**Comment by aaaidan** [comment]
Just to illustrate what part of the UI I mean...

![image](https://user-images.githubusercontent.com/151507/69024730-e28f7780-0978-11ea-8e74-720704709660.png)

**Comment by tbm98** [comment]
why you don't do it in local(IDE)

**Comment by aaaidan** [comment]
@tbm98 Thanks for the reminder! Do you mean that as a workaround, or do you not think this sort of functionality belongs in GF?

**Comment by GitFiend** [comment]
I often discard lines in my IDE, but usually want to stage them in GitFiend.

I put this off initially because if selection of lines isn't really good, this feature wouldn't add any value.

I think this should be part of future improvements to the code viewer.
