### ISSUE TITLE
No Authorization window is shown when cloning remote repo 

### ISSUE THREAD

**Issue by binaryblood** [GitFiend/Support#38]
GitFiend opens an already cloned repo, but when cloning a remote repo, it fails it never asks for authentication. The below error was shown in Ubuntu 16.04
![image](https://user-images.githubusercontent.com/31054280/69328596-83ca4680-0c75-11ea-8323-b72271ae2942.png)

**Comment by GitFiend** [comment]
Thanks binaryblood, I'll look into it.

**Comment by GitFiend** [comment]
I'm having trouble reproducing this. Are you trying to clone a private repo over https? I just tried this in Ubuntu 16.04.6 without any issues.

**Comment by binaryblood** [comment]
Yes, Its a private repo hosted with Gitea. its over HTTP (not https).

**Comment by binaryblood** [comment]
I guess the problem might have occured when this application tries accessing CURL library internally (That is what i see in the error message from the image).

**Comment by GitFiend** [comment]
Yeah. I seems the bundled git depends on it somehow and can't find/open it. 

In the latest version of GitFiend (0.21) there's an option to use your system git instead of the bundled one on linux. It's under main menu -> Repo. If git is working for you at the command line then this should work.
