### ISSUE TITLE
[Feature Request] Clone button

### ISSUE THREAD

**Issue by michelseiler** [GitFiend/Support#41]
Hello again
I think your project is very promising so I would like to place another request.
I would like to use your application for users who have no knowledge of vcs systems. It would be nice if the "most important" functions are easy to find. A clone button or at least a menupoint for cloning in the project repository dropdown would be desirable.
Like other authors, I would welcome if this project would become open-source.
Thank you for your work!

**Comment by GitFiend** [comment]
Hi @michelseiler.

Thanks for pointing this out, I do think clone is a bit too buried. 

If you are seeing users new to version control using GitFiend I would love to hear what they struggle with most.

**Comment by GitFiend** [comment]
I've added clone to the Repository menu in the toolbar in v0.23.
