### ISSUE TITLE
Can't open the .appimage on Manjaro

### ISSUE THREAD

**Issue by LoiLock** [GitFiend/Support#43]
So I downloaded the appimage from your website, gave it permissions to be executed. But when opened via the terminal using ./GitFiend-0.20.3.AppImage it gives me this error:
bash: ./GitFiend-0.20.3.AppImage: cannot execute binary file: Exec format error
Is it by any chance compiled for 32bit?
I'm running this on Manjaro using the 5.3.15-1 kernel

**Comment by GitFiend** [comment]
@LoiLock A possible work around while I look into this is to install GitFiend from AUR. 

https://aur.archlinux.org/packages/gitfiend/

Note: This package was created by Erik Dubois, not me.

**Comment by LoiLock** [comment]
Oh damn, I looked for it on the aur yesterday (or the day before, don't remember) and I couldn't find it. Thanks a lot though, I'll install it tomorrow morning!

**Comment by GitFiend** [comment]
I think this has since been fixed.
