### ISSUE TITLE
'flash' on menus when using Dark theme

### ISSUE THREAD

**Issue by chaeronius** [GitFiend/Support#47]
Using the Dark theme in GitFiend_0.21.3 a momentary white 'flash' appears after triggering a menu or submenu. 

Once a submenu has been triggered the effect seems to disappear from that menu until the parent menu is triggered again. This makes me think it is related to caching?

The effect happens during the time it takes the 'darkenBackground' class to be applied.

This happens on Mate ( on Debian 9.9 ) and Moksha ( on Bodhi 5.1 ) and was not present in GitFiend_0.20.3

**Comment by GitFiend** [comment]
Thanks @chaeronius. This bugs me as well. Unfortunately, I think it's a bug in the framework i'm using. I'm considering switching to my own implementation if it's not fixed soon.

**Comment by martinschayna** [comment]
Also seen and reported to vscode https://github.com/microsoft/vscode/issues/76850

**Comment by GitFiend** [comment]
This should be fixed now.

**Comment by chaeronius** [comment]
Confirmed on Linux, thanks
