### ISSUE TITLE
[Question] Updating GitFiend in Linux

### ISSUE THREAD

**Issue by geozeke** [GitFiend/Support#48]
Greetings!

This is an ***outstanding*** project -- really nice work.

I'm just curious about installing updates to GitFiend.  I currently install it in Ubuntu Linux using:

```Shell
wget -v https://gitfiend.com/resources/GitFiend_0.21.3_amd64.deb
sudo apt -y install ./GitFiend_0.21.3_amd64.deb
rm GitFiend_0.21.3_amd64.deb
```

When a new version of GitFiend is released, is it okay to install it on top of the old one?

Thanks!

**Comment by GitFiend** [comment]
Hi @geozeke. Thanks!

Installing over the previous version should be fine.

**Comment by geozeke** [comment]
Thanks!
