### ISSUE TITLE
Name Icon not displaying properly when person has a middle name

### ISSUE THREAD

**Issue by karamdaddy** [GitFiend/Support#5]
Hey Toby!

Found an edge case in the name icon. Middle names break the formatting.
Example: John man Doe will just display the first name

<img width="267" alt="Screen Shot 2019-08-08 at 10 40 59 AM" src="https://user-images.githubusercontent.com/11530737/62662811-65dc1d00-b9c9-11e9-913d-a7c8b41901ff.png">

**Comment by GitFiend** [comment]
Hey Karam. Thanks. This is more of an intentional bail out than a break. I think names get very complicated as soon as there's 3 or more words. I'm not sure whether I should take initials from the first and last words, or use all 3.

**Comment by karamdaddy** [comment]
Fair enough, thought I'd raise it just in case you didn't encounter it :)

Closing the issue :)
