### ISSUE TITLE
When will you release new version?

### ISSUE THREAD

**Issue by Abraxelx** [GitFiend/Support#52]
Hello can you give an information about new version for linux?
What's changelog exactly and when will it release?

**Comment by GitFiend** [comment]
Hi @Abraxelx. There's a new release coming soon, I'm just fixing the last few bugs. I normally try to release every 2 months or more, but this one is taking a little longer.

This release is mostly focused on performance, bug fixes and tweaks with a couple new features. 

I'll have a think about how to make this information more available in future.

**Comment by GitFiend** [comment]
New version for linux is out now.
