### ISSUE TITLE
Missing commits when undo a commit

### ISSUE THREAD

**Issue by Richard-Bagriy** [GitFiend/Support#54]
Hello i found some issue when i Undo my commit... 
For example i need to undo this commit test in the red border
![issue-1](https://user-images.githubusercontent.com/57046082/76069709-f698cc80-5f9b-11ea-9c4e-541a0f0b3403.png)
When I undo commit i can't see my all commits, i need to restart app..
![issue-2](https://user-images.githubusercontent.com/57046082/76069895-49728400-5f9c-11ea-9570-3b9648d29466.png)

For help
I'm using Linux Debian 10 and the last version of GitFiend 0.22.4

**Comment by GitFiend** [comment]
Thanks, @Richard-Bagriy, I'll look into this now.

**Comment by GitFiend** [comment]
I've just released GitFiend v0.22.6 to fix this. Thanks for letting me know.

**Comment by Richard-Bagriy** [comment]
Thanks for the quick fix @GitFiend
