### ISSUE TITLE
[Feature Request] increase font size

### ISSUE THREAD

**Issue by githlp** [GitFiend/Support#58]
there is no option to increase the font size yet? - that would help to spot change details more quickly

**Comment by GitFiend** [comment]
Coincidentally, I was just working this last night. In the next release, you will be able to increase and decrease the zoom like you would in a web browser. I turned this off initially as it broke context menus.

**Comment by githlp** [comment]
Great news - looking forward to the next release!

**Comment by GitFiend** [comment]
This was included in v0.23.
