### ISSUE TITLE
Add tree to GitFiend

### ISSUE THREAD

**Issue by qell** [GitFiend/Support#6]
I think it nice feature add tree git branches and commit like below pic:
![image](https://user-images.githubusercontent.com/41490584/63576552-b12b2980-c58c-11e9-9407-4ae49ed045f4.png)

**Comment by GitFiend** [comment]
This is by design. There are already arrows which allow you to see the relationship between commits and branches. I plan to add more features to improve this, but I don't want to do it the same way as other git clients as I don't like UI clutter.
