### ISSUE TITLE
Extending `git push` to handle pre-push hooks

### ISSUE THREAD

**Issue by karamdaddy** [GitFiend/Support#60]
Some repos have pre-push scripts that need to run (and pass) before the push happens.

Some hooks include checking the lint and running unit tests.

My workflow involves committing inside of GitFiend, and then switching over to the command line to run `git push`. Currently the push feature in GitFiend returns a `error: failed to push refs to {repo}` message.

**Comment by GitFiend** [comment]
Hey @karamdaddy :)

Thanks for letting me know. It's an interesting problem as I imagine I would also want to see some console output while it's running. I'll have a think about it. I like this idea; I should be running the gitfiend unit tests pre-push.
