### ISSUE TITLE
[Feature Request] Ability to swap Stage Hunk and Discard Hunk buttons placement

### ISSUE THREAD

**Issue by smujaddid** [GitFiend/Support#62]
I think it is more suitable to have the "Stage Hunk" button placed after "Discard Hunk" button, at least for my taste.

I already made my habit to move my mouse cursor to the rightmost button, which is usually "Stage Hunk" or "Stage File" in my case, when using other Git GUI apps. It is almost the same for me when using other apps.

Sometimes I made big mistakes by clicking "Discard Hunk" when using this app, even when the discard button already has different color than rest of buttons. I don't blame GitFiend design, but it is just a little inconvenient for me to have the discard button to be rightmost button because of my habit. So, it is nice to be able to swap them instead.

Thanks.

**Comment by GitFiend** [comment]
Hi @smujaddid. Thanks for bringing this up. I'm sorry to hear how easy it is to accidentally click discard hunk instead of stage hunk. I might agree about the button order, I'll have a think about this.

**Comment by smujaddid** [comment]
Thanks for considering this.

Maybe some users will disagree with this, so if there is a configuration to swap them for some users rather than change them permanently for all users might be a better solution, but that depends of its implementation.

Anyway, I'll accept your decision then whatever it is.

**Comment by smujaddid** [comment]
Thanks for implementing this in the new released version.
