### ISSUE TITLE
[feature request] configure tab spacing

### ISSUE THREAD

**Issue by fbstj** [GitFiend/Support#63]
I've gotten used to 2/3 spaced tabs, is there any chance I can reduce the tab spacing from 8 so things don't get pushed off the side of the page?

**Comment by GitFiend** [comment]
Oh, that's interesting. I prefer 2/3 space width also. I'm usually dealing spaces instead of tabs so I haven't been seeing this. I may need to add an option.

**Comment by GitFiend** [comment]
I've just released GitFiend v0.23 which improves this. Tab size is now 4 spaces. I think I will add an option in the future but wanted to do something better than 8 spaces quickly.
