### ISSUE TITLE
Support for Credential Helper

### ISSUE THREAD

**Issue by johncrenshaw** [GitFiend/Support#64]
GitFiend appears to ignore the credential helper, whether it is configured in the system, or in the repo. This is necessary to use AWS CodeCommit repos, among other things. Are there any workarounds, or is there any plan to support this?

**Comment by GitFiend** [comment]
It doesn't currently respect the users setting on Windows. It should be on Mac and Linux. I've been meaning to improve this.

**Comment by GitFiend** [comment]
@johncrenshaw This should be fixed in GitFiend v0.23. Thanks for reporting it.
