### ISSUE TITLE
+N refs animation edge case

### ISSUE THREAD

**Issue by fbstj** [GitFiend/Support#65]
if you hover over the end of the `+N` extra branches label in the Commits list it can cause animation flicker where the `+N` is removed which "shrinks" the label from under the mouse cursor causing animation cancellation then looping when the `+N` is added back in.

in the case i found it was `O local/master` `+2` and hovering close to the border would be enough to trigger the looping, as either the eventual label wasn't long enough or the in-between state was enough to cause cancellation.

**Comment by GitFiend** [comment]
Yeah, it's a bit flaky right now. I'm thinking of changing this so that you need to click on the `+2` to expand the stack. I want to move away from hover effects that move elements around.
