### ISSUE TITLE
[Feature Request] Tag creation

### ISSUE THREAD

**Issue by itspreshu** [GitFiend/Support#66]
It would be useful to have the tag feature on GitFiend, create tags, checkout tags, etc.

Great Work !

**Comment by itspreshu** [comment]
Looking a bit more I found this feature. My bad.

Great Work Anyways!

**Comment by GitFiend** [comment]
Glad you found it. The feature does need a bit more work.

**Comment by mukuact** [comment]
Excuese me.

I know how to create tag. But I could not find how to checkout tags. 
Would you tell me the way to checkout a tag?

**Comment by GitFiend** [comment]
Thanks @mukuact. There's currently no feature to make a branch and checkout from a tag. You can make the branch by going to the commit the tag is on directly.

**Comment by mukuact** [comment]
OK.
