### ISSUE TITLE
[Feature requests] Display date and time of commit

### ISSUE THREAD

**Issue by lysek** [GitFiend/Support#69]
It would be nice to have exact date and time of commit somewhere in commit details along with "XY days ago". Thanks.

**Comment by houdinihound** [comment]
If you hover over "XY days ago" you get the exact timestamp, at least on my version, 0.23 (linux).  Does yours not show this?

**Comment by lysek** [comment]
Yes, I haven't noticed this feature. But still, it would be good to see exact time and date somewhere in the commit details, there is plenty of space - e.g. next to commit hash.
