### ISSUE TITLE
Gitfiend won't log me in

### ISSUE THREAD

**Issue by SincerelyFaust** [GitFiend/Support#75]
So I stage my changes and it asks for my Username and Password which I enter, after that it just resets, doesn't push and when I click Push again, asks for the same again.
My GitHub account has 2FA, maybe it doesn't like that?
I'm on Linux (elementaryOS) at the moment, on Windows it worked perfectly.

**Comment by GitFiend** [comment]
On Linux you will need to use a personal access token instead of your password if you are using 2fa. Sorry that the UI doesn't explain this.

**Comment by SincerelyFaust** [comment]
I see, thanks and you should totally add that to the UI 😅
