### ISSUE TITLE
Dark theme not persist

### ISSUE THREAD

**Issue by qell** [GitFiend/Support#8]
On linux(debian 10) the switch to dark theme is not persist. App have any config file to save settings permanently?

**Comment by GitFiend** [comment]
That's strange. I'm using ubuntu and it's persisting the theme. It remembers it the same way it remembers which repo you had open. Does it remember the last open repo?

**Comment by qell** [comment]
No it doesn't. Maybe app haven't permission to save config file?

**Comment by GitFiend** [comment]
It could be. I can do some testing on Debian when I get time. Do you have multiple instances of GitFiend open?

**Comment by qell** [comment]
I just run one instance and nothing more.
