### ISSUE TITLE
Long repository name

### ISSUE THREAD

**Issue by rahmaevao** [GitFiend/Support#81]
I have a long repository name.
The repository name bumps into the branches tab.

![image](https://user-images.githubusercontent.com/33318971/100706350-eb06f480-33b9-11eb-8379-df977f8068c7.png)
GitFiend_0.24.1_amd64 Ubuntu

**Comment by GitFiend** [comment]
Wow, you do indeed. Thanks, I'll see what I can do to improve this.

**Comment by GitFiend** [comment]
This should be fixed now.
