### ISSUE TITLE
Use git stored credentials

### ISSUE THREAD

**Issue by earnestma** [GitFiend/Support#82]
Would it be possible for GitFiend to use Git stored credentials?

~/.gitconfig:
```
[credential]
	helper = store
```

Credentials are stored in plain text in ~/.git-credentials or $XDG_CONFIG_HOME/git/credentials 

GitFiend 0.24.1.0
git version 2.29.2.windows.2

Thanks!

**Comment by GitFiend** [comment]
You may be able to get this working by using the .exe installer of GitFiend and your system installed version of Git (uncheck menu -> repo -> use build-in git). You should then be able to set the credential helper in your Git config to use store instead.

Some details:
 - The Windows Store version of GitFiend includes an embedded copy of Git and git-credential-manager (this is a requirement of the MS Store)
 - The .exe installer version of GitFiend includes the embedded version of Git, but you can switch to use the system one.
 - The Linux and Mac versions don't include it and just use your system installed version.

**Comment by earnestma** [comment]
Thank you!
