### ISSUE TITLE
Application icon missing for AppImage shortcut

### ISSUE THREAD

**Issue by igorpupkinable** [GitFiend/Support#83]
Given I have `/opt/GitFiend-0.24.1.AppImage`, I have added desktop entry to `~/.local/share/applications/GitFiend.desktop` with the following content:
```
[Desktop Entry]
Name=GitFiend
Comment=A Git client designed for humans.
Exec="/opt/GitFiend-0.24.1.AppImage" %U
Terminal=false
Type=Application
Icon=gitfiend    <= what is correct name/path to bundled icon here?
StartupWMClass=GitFiend
Categories=Development;
```

I can launch the app and everything works. Icon is missing however.
What is the correct path/name for application icon?

I can help updating documentation with this example if anyone knows how to get application icon from the AppImage.

Ubuntu 18LTS x64

**Comment by GitFiend** [comment]
I don't know a lot about the AppImage format but it sounds like you would need to extract it first which seems extreme. 

You could try these options if you haven't already:

A) Using the icon from gitfiend.com
B) Installing the .deb version of GitFiend
C) Install something that improves the AppImage integration in your distro

**Comment by igorpupkinable** [comment]
I found a way to do this manually after some investigation.

To add a shortcut icon you need to extract if first from AppImage with `./GitFiend-0.25.4.AppImage --appimage-extract`. You will find `gitfiend.png` which you need to copy to `/var/lib/snapd/desktop/icons`. Icon will be picked up automatically after for a desktop entry with `Icon=gitfiend` property.

However, I am yet to figure out how to use icon from the AppImage bundle directly, which is not described in specification, but works for other apps downloaded as Snaps via Ubuntu Software.

- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
- https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
