### ISSUE TITLE
GitFiend not seeing commits and branches

### ISSUE THREAD

**Issue by ghost** [GitFiend/Support#84]
Cloned a repository from BitBucket. It is a big repository with multiple branches, thousands of commits. When opened in GitFiend, I see **nothing**. No branches, no commits, _no nothing_. This is especially weird, since I have some other local repos, and GitFiend sees them properly and all. I do not even know how to debug this. I can see the commits and branches when accessing via Git from Terminal. Using GitFiend 0.24.1 on macOS Big Sur with Intel.

**Comment by GitFiend** [comment]
Thanks for the bug entry. This is strange. Something that would help is if you could open the dev tools: View -> Toggle Developer Tools, and see if there are any error messages. There's also a chance this is related to Big Sur as I haven't released an updated version yet.

**Comment by GitFiend** [comment]
Any chance you used a shallow clone? I haven't seen how this behaves in GitFiend yet. Other ideas is there's something unexpected in your commit messages or time stamps GitFiend doesn't know how to handle.

**Comment by mateuszjablonski** [comment]
after typing `git fetch --unshallow` I get `fatal: --unshallow on a complete repository does not make sense`. Is there some kind of debug mode, so I can see what Git commands are called and what is the result?

I don't think it has anything to do with branch or commit names, using only regular English characters.

After giving it some thought, it looks like it has problems with determining remotes - I am unable to fetch (button is disabled), until I push - then the button unlocks. Maybe this is the route we should investigate. Is there any way to look up Git commands called and responses received by GitFiend? Some kind of verbose mode.

**Comment by DennisBetawerk** [comment]
I'm having the same problem. Whenever a specific team member makes a commit on a branch (even one that is not my current branch), everything including and before that commit is completely invisible in GitFiend. No remotes, commits or branches. If I create a new commit and push it through the CLI, that commit, remote and branch show up again, but only from my commit onwards.

Looking at the commits from that person, I see that they are listed as author `Firstname Lastname <>` (no email address), could that be confusing GitFiend somehow?

**Comment by mateuszjablonski** [comment]
@DennisBetawerk YES! It makes perfect sense. I have three separate repos, two of them are failing to work with GitFiend, and I have just checked, that in both of them there are some authors with no email address. The third one works, because it is my private repo and I am the only committer.

**Comment by GitFiend** [comment]
Thanks @DennisBetawerk and @mateuszjablonski for investigating, that might be the problem. I'll look into it first thing.

**Comment by DennisBetawerk** [comment]
With release 0.26 I can see all commits again, even those by people without an email address. Thank you!

**Comment by GitFiend** [comment]
Excellent, Thanks.

**Comment by mateuszjablonski** [comment]
I know the issue is closed now, but I want to confirm, that it was the exact issue on my side too. Now after update I can see all the commits and branches. Thanks @GitFiend for the good work! I have bumped the version on Homebrew.
