### ISSUE TITLE
Operation hangs until "show console" is clicked

### ISSUE THREAD

**Issue by SecondFlight** [GitFiend/Support#85]
This happens with other operations intermittently, but I can reproduce it on Windows 10 with these steps:

1. Make some changes to the repo
2. Close and re-open GitFiend
3. Stage a file

This causes the in-progress popup to stay on screen. If I click "show console" and then "OK", it closes. Otherwise, I have to wait for something like 30 seconds.

This also happens when you first unstage a file after restarting GitFiend.

**Comment by GitFiend** [comment]
Thanks @SecondFlight. I've just released GitFiend 0.25.4 which should fix this (Microsoft store version should be available soon).

**Comment by SecondFlight** [comment]
Confirmed fixed in the 0.25.4.0. Thanks!
