### ISSUE TITLE
Line-by-line discard is broken

### ISSUE THREAD

**Issue by SecondFlight** [GitFiend/Support#86]
In the latest update, line-by-line discard is broken (Windows 10):

![Ho77KDPxMa](https://user-images.githubusercontent.com/6700184/108585900-01698000-7319-11eb-97ba-823f2bc19994.gif)

The "show console" workaround seen above is described in #85.

**Comment by GitFiend** [comment]
Thanks @SecondFlight, this was very helpful. I've just released GitFiend 0.25.4 with a fix for this (Microsoft store version should be available soon).

**Comment by SecondFlight** [comment]
Confirmed fixed in the 0.25.4.0. Thanks!
