### ISSUE TITLE
[Feature Request] Option to enable lines between commit dots

### ISSUE THREAD

**Issue by Industrial** [GitFiend/Support#87]
Hi!

I understand that it's part of the design but working in a team and having many branches it's very confusing to see one line of commits when it's different work being done by multiple people simultaneously.

To make this process understandable the command-line git client includes this functionality as well (`git log --graph --oneline`) so I think it should not be missing from a GUI client.

Could you make it an option so people who prefer to see branch lines can see them?

gr,

Tom

p.s. great piece of software!

**Comment by GitFiend** [comment]
Hi Tom, thanks.

Something I'm planning to work on soon is the ability to set filters. You could use this to exclude commits that are not on your current branch. Would this help?
