### ISSUE TITLE
Invalid version at https://gitfiend.com/app-info

### ISSUE THREAD

**Issue by mateuszjablonski** [GitFiend/Support#88]
Currently https://gitfiend.com/app-info returns version `0.25.0`, but there is no such version. There is `0.25.4` available at https://gitfiend.com/resources/GitFiend-0.25.4.dmg. Reporting because of failed update submission to Homebrew Cask: https://github.com/Homebrew/homebrew-cask/pull/100137

**Comment by GitFiend** [comment]
That's strange. I'll take a look at it later today when I get time. Thanks for reporting.

**Comment by GitFiend** [comment]
This should be fixed now.

**Comment by mateuszjablonski** [comment]
Yes, version is now `0.25.4`
