### ISSUE TITLE
changes view - annoying hover animation

### ISSUE THREAD

**Issue by martin8877** [GitFiend/Support#89]
Hi, 
Is it possible to disable hover animation when staging files? I often click on "Stage File" or "Unstage file" by accident when comparing changes. I think it's UX anti-pattern if button changes position on mouse hover. It would be more intuitive if these buttons were always visible.

btw, great git client

**Comment by GitFiend** [comment]
Yeah, I agree it's a problem. I'm planning to redesign both this and the branch hovering soon so that things only move on clicking.
