### ISSUE TITLE
large list for recent GIT

### ISSUE THREAD

**Issue by navalpatel5** [GitFiend/Support#92]
Thanks for a very valuable and useful tool. It has never once made me look for anything else to solve the GIT related operations.

There are about more than 15 -20 projects I keep working/visiting in a week. The recent repository list or the list of repositories that are available to switch between are only 8. Was wondering if there is some configuration/setting by which I can increase the list size, then I am sure it will be extremely helpful for many.

Please let me know if this can be done on current verison of the software.

**Comment by GitFiend** [comment]
Thanks for the comments @navalpatel5.

Unfortunately, there's no current way to change the size of the list. I had a look at other apps, and I think the size should probably be doubled.

**Comment by GitFiend** [comment]
The size of the list has been increased. I'm also working on a multi repo feature that may further improve this in the future.
