### ISSUE TITLE
Remove "stage file" slider

### ISSUE THREAD

**Issue by ad-si** [GitFiend/Support#93]
I think this is a really bad design in terms of UX.

It happened a few times already that I wanted to click on a file to view it in the diff view on the right side, but I didn't take into consideration, that the "stage file" button slides out, and so I accidentally clicked on "stage file" instead.

GitUp lets you simply stage a file by double clicking it. If that's not discoverable enough for your, there could also be a permanent button.

Also not bad are check boxes as GitAhead uses it:

![image](https://user-images.githubusercontent.com/36796532/114369880-5cc42b80-9b6e-11eb-9b9a-58965cd06169.png)

**Comment by GitFiend** [comment]
Yeah, I agree. See https://github.com/GitFiend/Support/issues/89

**Comment by GitFiend** [comment]
This has been changed quite a lot and there are no longer any sliding buttons. 

@acarv Let me know if you are still having problems. The stage-all button is gone. Instead there's a checkbox at the top to select all files to be included in the commit.
