### ISSUE TITLE
bug detected / found

### ISSUE THREAD

**Issue by ProgrammerAuditore** [GitFiend/Support#95]
There is a bug when deleting a branch in Windows, it enters an infinite loop with a message that says "Delete <name_branch> ..." and it is necessary to close the program.

**Comment by GitFiend** [comment]
Thanks, @ProgrammerAuditore. I think I may have seen this once before but haven't been able to reproduce it since. Does this happen for all branches? Or just some? Can you provide some details about this branch? is it local or remote? Does its name have non-alphabet characters?

**Comment by SergeyFi** [comment]
Hello, I have the same bug, in my case it happened in locally on any brunch. name of the branch has only alphabet characters.

**Comment by GitFiend** [comment]
I've been able to reproduce this. Thanks @SergeyFi and @ProgrammerAuditore. I'll have a fix out soon.

**Comment by GitFiend** [comment]
This should be fixed now. Let me know if it's still a problem.
