### ISSUE TITLE
Support Markdown emoji

### ISSUE THREAD

**Issue by Sebclem** [GitFiend/Support#97]
I'm using a lot of markdown emoji in my commits message, but in GitFiend, the emoji are not parsed:  
![image](https://user-images.githubusercontent.com/23737709/120812070-f4317380-c54c-11eb-93f6-434b9eff64a0.png)

You can maybe use this https://github.com/omnidan/node-emoji :
```node
var emoji = require('node-emoji')
emoji.emojify('I :heart: :coffee:!')  // replaces all :emoji: with the actual emoji, in this case: returns "I ❤️ ☕️!"
```

**Comment by GitFiend** [comment]
Thanks, @Sebclem. I think this is worth doing. Are you using markdown emoji instead of Unicode for any particular reason? The native emoji picker should work in GitFiend on Mac and Windows, but unfortunately not Linux.

**Comment by Sebclem** [comment]
I, sorry for this (verry :sweat_smile: ) late reply, i was quite busy, i'm mostly on linux and i write a lot of docs in Markdown at work so it's more a habit now.
And I think the KDE emoji picker work (i need to try to be sure). But if GitFiend can parce markdown emoji this will be perfect.

**Comment by GitFiend** [comment]
This was added in v0.29. Hopefully this helps.
